### ISSUE TITLE
docs: consolidated user guide improvement suggestions

### ISSUE THREAD

**Issue by jinxuan-owyong** [AY2223S2-CS2113-W15-2/tp#201]
__The following issues are consolidated from PE-D__

- [x] only first valid entry after input flag is accepted (#158, #169, #170)
- [x] use one flag variant once (#162, #164, #166, #173, #176, #183, #189)
- [x] negative prices not accepted (#159)
- [x] clarity on usage and behaviour of flags (#163, #177, #179)
- [x] clarity of `COUNT` parameter in `/view` (#165, #180)
- [x] edit command: flags should be specified (#168)
- [x] rounding off of prices (#171, #185)
- [x] case insensitivity for category (#172)
- [x] command summary inconsistency and cosmetic issues (#182, #193, #199)
- [x] introduce categories before features (#167, #198)
- [x] provide guides on how to use flags (#161, https://github.com/AY2223S2-CS2113-W15-2/tp/issues/161#issuecomment-1492797773)
