### ISSUE TITLE
`Parser`: consolidated improvement suggestions

### ISSUE THREAD

**Issue by jinxuan-owyong** [AY2223S2-CS2113-W15-2/tp#205]
__The following issues are consolidated from PE-D__

- [x] throw exception when more than one flag variant is used (#162, #166, #183)
- [x] throw exception when no edit flags are present (#168)
- [x] limit number of digits allowed for price (#171, #191, #196)
- [x] date parsing issue (#174)
- [x] show more meaningful exception message for invalid indices (#190)
- [x] allow certain special characters (#184)
- [x] reject zero dollar amount (#187)

**Comment by jinxuan-owyong** [comment]
All tasks have been completed. This issue will be closed.
